### ISSUE TITLE
Can't find usage of CGR in code

### ISSUE THREAD

**Issue by TomerAntman** [Kari-Genomics-Lab/iDeLUCS#1]
Hi there, 
I really liked your work and the GUI is great! I tried to use it on my bacterial community fasta file (long reads from pacbio) and didn't manage to get a good separation for the genus level. I wanted to extract the FCGR 2d vector from the code and couldn't manage to do so, which brings me to my question:
**Where do you use FCGR in this code?**
The only lines I found that mention cgr appear to be silenced (example below). Could you comment on that?
 
https://github.com/Kari-Genomics-Lab/iDeLUCS/blob/4d47b280ab9746d526c7ce2cf54d7206bb16c897/src/utils.py#L207

**Comment by millanp95** [comment]
Hi, sorry for the late response. For now, the linear architecture has worked well for our experiments. We are still testing the 2D fCGR architecture, which is why this line is commented out. You can still use that function to produce the fCGR and use that in your analyses.

If you want to test the performance yourself, you can uncomment that line and use the option --model_size='full' in the CLI application to try out the ResNet, but there is no guarantee that it is going to work.

 For pacbio sequences, we've had good results with k=6 and w=0.5 with a small microbiome
